// Build script for USBVault Crypto FFI
// Generates C headers from Rust FFI exports using cbindgen

fn main() {
    #[cfg(feature = "ffi")]
    {
        use std::env;
        use std::path::PathBuf;

        let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

        // Build cbindgen config via a struct literal with `..Default::default()`.
        // cbindgen 0.29's `Config` fields are public, so this is the idiomatic
        // form (clippy's `field_reassign_with_default` rejects the older
        // default-then-assign pattern under `-D warnings`).
        let config = cbindgen::Config {
            header: Some(
                "// Auto-generated C header for USBVault Crypto FFI\n\
                 // Generated by cbindgen\n\
                 #pragma once\n\n\
                 #include <stddef.h>\n\
                 #include <stdint.h>"
                    .to_string(),
            ),
            documentation: true,
            documentation_style: cbindgen::DocumentationStyle::C99,
            ..Default::default()
        };

        // Generate to OUT_DIR
        match cbindgen::Builder::new()
            .with_crate(crate_dir.clone())
            .with_config(config.clone())
            .generate()
        {
            Ok(bindings) => {
                bindings.write_to_file(out_dir.join("usbvault_crypto.h"));
                println!("cargo:warning=Generated C headers to OUT_DIR");
            }
            Err(e) => {
                println!("cargo:warning=cbindgen failed for OUT_DIR: {e}");
            }
        }

        // Also write to project root for easy access
        match cbindgen::Builder::new()
            .with_crate(crate_dir)
            .with_config(config)
            .generate()
        {
            Ok(bindings) => {
                bindings.write_to_file("usbvault_crypto.h");
                println!("cargo:warning=Generated C headers to project root");
            }
            Err(e) => {
                println!("cargo:warning=cbindgen failed for project root: {e}");
            }
        }
    }

    #[cfg(not(feature = "ffi"))]
    {
        // FFI feature not enabled, nothing to generate
    }
}
