// Build script for QAV Crypto FFI
// Generates C headers from Rust FFI exports using cbindgen

#[cfg(feature = "ffi")]
fn main() {
    use std::env;
    use std::path::PathBuf;

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Generate C headers for FFI exports
    let config = cbindgen::Config {
        header: Some("// Auto-generated C header for QAV Crypto FFI\n// Generated by cbindgen\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>".to_string()),
        documentation: true,
        documentation_style: cbindgen::DocumentationStyle::C99,
        ..Default::default()
    };

    cbindgen::Builder::new()
        .with_crate(crate_dir.clone())
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(out_dir.join("usbvault_crypto.h"));

    // Also write to a more accessible location in the project root
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(cbindgen::Config {
            header: Some("// Auto-generated C header for QAV Crypto FFI\n// Generated by cbindgen\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>".to_string()),
            documentation: true,
            documentation_style: cbindgen::DocumentationStyle::C99,
            ..Default::default()
        })
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("usbvault_crypto.h");

    println!("cargo:warning=Generated C headers for FFI exports");
}

#[cfg(not(feature = "ffi"))]
fn main() {
    println!("cargo:warning=FFI feature not enabled, skipping header generation");
}
