// Auto-generated C header for QAV Crypto FFI
// Generated by cbindgen
#pragma once

#include <stddef.h>
#include <stdint.h>

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Wrapped MEK blob: nonce(24) || ciphertext(64+16) = 104 bytes
constexpr static const uintptr_t WRAPPED_MEK_SIZE = ((24 + 64) + 16);

// Default threshold for MEK recovery (minimum shares needed)
constexpr static const uint8_t DEFAULT_THRESHOLD = 3;

// Default total shares to generate
constexpr static const uintptr_t DEFAULT_TOTAL_SHARES = 5;

// g = generator (always 2 for RFC 7919)
constexpr static const uint32_t G = 2;

// Minimum chunk size for streaming encryption (4 KB)
constexpr static const uintptr_t MIN_CHUNK_SIZE = 4096;

// Maximum chunk size for streaming encryption (64 MB)
constexpr static const uintptr_t MAX_CHUNK_SIZE = ((64 * 1024) * 1024);

// Default chunk size for streaming (64 KB)
constexpr static const uintptr_t CHUNK_SIZE = 65536;

// V2 header size (4096 bytes)
constexpr static const uintptr_t HEADER_SIZE_V2 = 4096;

// V3 header size (16384 bytes)
constexpr static const uintptr_t HEADER_SIZE_V3 = 16384;

// V4 header size (24576 bytes = 24KB for wrapped MEK + encrypted index)
constexpr static const uintptr_t HEADER_SIZE_V4 = 24576;

// ML-KEM-1024 public key size in bytes
constexpr static const uintptr_t PUBLIC_KEY_SIZE = 1568;

// ML-KEM-1024 ciphertext size in bytes
constexpr static const uintptr_t CIPHERTEXT_SIZE = 1568;

// ML-KEM-1024 shared secret size in bytes
constexpr static const uintptr_t SHARED_SECRET_SIZE = 32;

extern "C" {

// Derive master key from password
//
// # Safety
// Caller must ensure:
// - password_ptr is valid and password_len is correct
// - salt_ptr is valid and salt_len is 32
// - out_ptr can hold 64 bytes
// - out_len pointer is valid for writing
int32_t qav_derive_key(const uint8_t *password_ptr,
                       uintptr_t password_len,
                       const uint8_t *salt_ptr,
                       uintptr_t salt_len,
                       uint8_t *out_ptr,
                       uintptr_t *out_len);

// Encrypt plaintext
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t qav_encrypt(uint8_t cipher_id,
                    const uint8_t *key_ptr,
                    uintptr_t key_len,
                    const uint8_t *plaintext_ptr,
                    uintptr_t plaintext_len,
                    uint8_t *out_ptr,
                    uintptr_t out_capacity,
                    uintptr_t *out_len);

// Decrypt ciphertext
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t qav_decrypt(uint8_t cipher_id,
                    const uint8_t *key_ptr,
                    uintptr_t key_len,
                    const uint8_t *ciphertext_ptr,
                    uintptr_t ciphertext_len,
                    uint8_t *out_ptr,
                    uintptr_t out_capacity,
                    uintptr_t *out_len);

// Generate X25519 keypair for sharing
//
// # Safety
// Caller must ensure:
// - public_out can hold 32 bytes
// - secret_out can hold 32 bytes
int32_t qav_generate_keypair(uint8_t *public_out, uint8_t *secret_out);

// Seal plaintext for a recipient
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t qav_seal(const uint8_t *recipient_public,
                 const uint8_t *plaintext_ptr,
                 uintptr_t plaintext_len,
                 uint8_t *out_ptr,
                 uintptr_t out_capacity,
                 uintptr_t *out_len);

// Open a sealed message
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t qav_open(const uint8_t *secret_key,
                 const uint8_t *sealed_ptr,
                 uintptr_t sealed_len,
                 uint8_t *out_ptr,
                 uintptr_t out_capacity,
                 uintptr_t *out_len);

// Free allocated memory
//
// # Safety
// Caller must ensure the pointer was allocated by this library
//
// # Note
// Memory is managed by Rust's allocator, so this function is not required.
// This function exists for C ABI compatibility but is a no-op since buffers
// are managed by Rust and should not be freed manually.
//
// Returns ERR_INVALID_ARGUMENT to indicate the function is not supported.
int32_t qav_free(uint8_t *_ptr, uintptr_t _len);

// Generate a random salt
//
// # Safety
// Caller must ensure out can hold 32 bytes
int32_t qav_generate_salt(uint8_t *out);

// Generate a hybrid X25519 + ML-KEM-1024 keypair
//
// # Safety
// Caller must ensure:
// - x25519_pub_out can hold 32 bytes
// - mlkem_pub_out can hold 1568 bytes
// - x25519_sec_out can hold 32 bytes
// - mlkem_sec_out can hold 1568 bytes
//
// # Returns
// ERR_SUCCESS (0) on success, or ERR_INVALID_ARGUMENT if pqc feature not enabled
int32_t qav_pqc_generate_keypair(uint8_t *x25519_pub_out,
                                 uint8_t *mlkem_pub_out,
                                 uint8_t *x25519_sec_out,
                                 uint8_t *mlkem_sec_out);

// Hybrid seal: encrypt plaintext for a recipient using X25519 + ML-KEM-1024
//
// # Safety
// Caller must ensure:
// - x25519_pub is 32 bytes (recipient X25519 public key)
// - mlkem_pub is 1568 bytes (recipient ML-KEM-1024 encapsulation key)
// - plaintext_ptr/plaintext_len are valid
// - out_ptr has capacity for sealed output (plaintext_len + 1640 overhead)
//
// # Format
// Output: x25519_eph(32) || mlkem_ct(1568) || nonce(24) || ciphertext || tag(16)
int32_t qav_pqc_seal(const uint8_t *x25519_pub,
                     const uint8_t *mlkem_pub,
                     uintptr_t mlkem_pub_len,
                     const uint8_t *plaintext_ptr,
                     uintptr_t plaintext_len,
                     uint8_t *out_ptr,
                     uintptr_t out_capacity,
                     uintptr_t *out_len);

// Hybrid open: decrypt a hybrid sealed message using X25519 + ML-KEM-1024
//
// # Safety
// Caller must ensure:
// - x25519_sec is 32 bytes (recipient X25519 secret key)
// - mlkem_sec is 1568 bytes (recipient ML-KEM-1024 decapsulation key)
// - sealed_ptr/sealed_len are valid
// - out_ptr has capacity for plaintext (sealed_len - 1640)
int32_t qav_pqc_open(const uint8_t *x25519_sec,
                     const uint8_t *mlkem_sec,
                     uintptr_t mlkem_sec_len,
                     const uint8_t *sealed_ptr,
                     uintptr_t sealed_len,
                     uint8_t *out_ptr,
                     uintptr_t out_capacity,
                     uintptr_t *out_len);

// JNI initialization
void Java_com_qav_crypto_CryptoLib_init(JNIEnv _env, JClass _class);

// JNI key derivation wrapper
void Java_com_qav_crypto_CryptoLib_deriveKey(JNIEnv _env, JClass _class);

} // extern "C"
