// Auto-generated C header for USBVault Crypto FFI
// Generated by cbindgen
#pragma once

#include <stddef.h>
#include <stdint.h>

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

// Wrapped MEK blob: nonce(24) || ciphertext(64+16) = 104 bytes
constexpr static const uintptr_t WRAPPED_MEK_SIZE = ((24 + 64) + 16);

// Default threshold for MEK recovery (minimum shares needed)
constexpr static const uint8_t DEFAULT_THRESHOLD = 3;

// Default total shares to generate
constexpr static const uintptr_t DEFAULT_TOTAL_SHARES = 5;

// g = generator (always 2 for RFC 7919)
constexpr static const uint32_t G = 2;

// Minimum chunk size for streaming encryption (4 KB)
constexpr static const uintptr_t MIN_CHUNK_SIZE = 4096;

// Maximum chunk size for streaming encryption (64 MB)
constexpr static const uintptr_t MAX_CHUNK_SIZE = ((64 * 1024) * 1024);

// Default chunk size for streaming (64 KB)
constexpr static const uintptr_t CHUNK_SIZE = 65536;

// V2 header size (4096 bytes)
constexpr static const uintptr_t HEADER_SIZE_V2 = 4096;

// V3 header size (16384 bytes)
constexpr static const uintptr_t HEADER_SIZE_V3 = 16384;

// V4 header size (24576 bytes = 24KB for wrapped MEK + encrypted index)
constexpr static const uintptr_t HEADER_SIZE_V4 = 24576;

// ML-KEM-1024 public key size in bytes
constexpr static const uintptr_t PUBLIC_KEY_SIZE = 1568;

// ML-KEM-1024 ciphertext size in bytes
constexpr static const uintptr_t CIPHERTEXT_SIZE = 1568;

// ML-KEM-1024 shared secret size in bytes
constexpr static const uintptr_t SHARED_SECRET_SIZE = 32;

extern "C" {

// Derive master key from password
//
// # Safety
// Caller must ensure:
// - password_ptr is valid and password_len is correct
// - salt_ptr is valid and salt_len is 32
// - out_ptr can hold 64 bytes
// - out_len pointer is valid for writing
int32_t usbvault_derive_key(const uint8_t *password_ptr,
                            uintptr_t password_len,
                            const uint8_t *salt_ptr,
                            uintptr_t salt_len,
                            uint8_t *out_ptr,
                            uintptr_t *out_len);

// Encrypt plaintext
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t usbvault_encrypt(uint8_t cipher_id,
                         const uint8_t *key_ptr,
                         uintptr_t key_len,
                         const uint8_t *plaintext_ptr,
                         uintptr_t plaintext_len,
                         uint8_t *out_ptr,
                         uintptr_t out_capacity,
                         uintptr_t *out_len);

// Decrypt ciphertext
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t usbvault_decrypt(uint8_t cipher_id,
                         const uint8_t *key_ptr,
                         uintptr_t key_len,
                         const uint8_t *ciphertext_ptr,
                         uintptr_t ciphertext_len,
                         uint8_t *out_ptr,
                         uintptr_t out_capacity,
                         uintptr_t *out_len);

// Generate X25519 keypair for sharing
//
// # Safety
// Caller must ensure:
// - public_out can hold 32 bytes
// - secret_out can hold 32 bytes
int32_t usbvault_generate_keypair(uint8_t *public_out, uint8_t *secret_out);

// Seal plaintext for a recipient
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t usbvault_seal(const uint8_t *recipient_public,
                      const uint8_t *plaintext_ptr,
                      uintptr_t plaintext_len,
                      uint8_t *out_ptr,
                      uintptr_t out_capacity,
                      uintptr_t *out_len);

// Open a sealed message
//
// # Safety
// Caller must ensure all pointers are valid and lengths are correct
int32_t usbvault_open(const uint8_t *secret_key,
                      const uint8_t *sealed_ptr,
                      uintptr_t sealed_len,
                      uint8_t *out_ptr,
                      uintptr_t out_capacity,
                      uintptr_t *out_len);

// Free allocated memory
//
// # Safety
// Caller must ensure the pointer was allocated by this library
//
// # Note
// Memory is managed by Rust's allocator, so this function is not required.
// This function exists for C ABI compatibility but is a no-op since buffers
// are managed by Rust and should not be freed manually.
//
// Returns ERR_INVALID_ARGUMENT to indicate the function is not supported.
int32_t usbvault_free(uint8_t *_ptr, uintptr_t _len);

// Generate a random salt
//
// # Safety
// Caller must ensure out can hold 32 bytes
int32_t usbvault_generate_salt(uint8_t *out);

// Generate a hybrid X25519 + ML-KEM-1024 keypair
//
// # Safety
// Caller must ensure:
// - x25519_pub_out can hold 32 bytes
// - mlkem_pub_out can hold 1568 bytes
// - x25519_sec_out can hold 32 bytes
// - mlkem_sec_out can hold 1568 bytes
//
// # Returns
// ERR_SUCCESS (0) on success, or ERR_INVALID_ARGUMENT if pqc feature not enabled
int32_t usbvault_pqc_generate_keypair(uint8_t *x25519_pub_out,
                                      uint8_t *mlkem_pub_out,
                                      uint8_t *x25519_sec_out,
                                      uint8_t *mlkem_sec_out);

// Hybrid seal: encrypt plaintext for a recipient using X25519 + ML-KEM-1024
//
// # Safety
// Caller must ensure:
// - x25519_pub is 32 bytes (recipient X25519 public key)
// - mlkem_pub is 1568 bytes (recipient ML-KEM-1024 encapsulation key)
// - plaintext_ptr/plaintext_len are valid
// - out_ptr has capacity for sealed output (plaintext_len + 1640 overhead)
//
// # Format
// Output: x25519_eph(32) || mlkem_ct(1568) || nonce(24) || ciphertext || tag(16)
int32_t usbvault_pqc_seal(const uint8_t *x25519_pub,
                          const uint8_t *mlkem_pub,
                          uintptr_t mlkem_pub_len,
                          const uint8_t *plaintext_ptr,
                          uintptr_t plaintext_len,
                          uint8_t *out_ptr,
                          uintptr_t out_capacity,
                          uintptr_t *out_len);

// Hybrid open: decrypt a hybrid sealed message using X25519 + ML-KEM-1024
//
// # Safety
// Caller must ensure:
// - x25519_sec is 32 bytes (recipient X25519 secret key)
// - mlkem_sec is 1568 bytes (recipient ML-KEM-1024 decapsulation key)
// - sealed_ptr/sealed_len are valid
// - out_ptr has capacity for plaintext (sealed_len - 1640)
int32_t usbvault_pqc_open(const uint8_t *x25519_sec,
                          const uint8_t *mlkem_sec,
                          uintptr_t mlkem_sec_len,
                          const uint8_t *sealed_ptr,
                          uintptr_t sealed_len,
                          uint8_t *out_ptr,
                          uintptr_t out_capacity,
                          uintptr_t *out_len);

// A1: Create a new V4 vault header from password.
//
// Returns header bytes (24576) + enc_key (32) + hmac_key (32) = 24640 bytes total.
// The enc_key and hmac_key are the MEK halves for immediate use.
// Caller MUST zero them after writing the initial empty index.
//
// # Safety
// - password_ptr/password_len: valid UTF-8 password
// - cipher_id: 2 (XChaCha20) or 3 (AES-GCM-SIV)
// - out_ptr: capacity >= 24640 bytes
// - out_len: valid pointer for writing
int32_t usbvault_vault_create_header(const uint8_t *password_ptr,
                                     uintptr_t password_len,
                                     uint8_t cipher_id,
                                     uint8_t *out_ptr,
                                     uintptr_t out_capacity,
                                     uintptr_t *out_len);

// A2: Parse header bytes into JSON metadata (no secrets exposed).
//
// Returns JSON string with: version, saltHex, activeIndexSlot,
// index1Offset, index1Length, index2Offset, index2Length,
// commitCounter, stateVersion, hasWrappedMek, indexEncrypted
//
// # Safety
// - header_ptr/header_len: valid header bytes
// - out_json_ptr: capacity for JSON string
// - out_json_len: valid pointer
int32_t usbvault_vault_read_header(const uint8_t *header_ptr,
                                   uintptr_t header_len,
                                   uint8_t *out_json_ptr,
                                   uintptr_t out_json_capacity,
                                   uintptr_t *out_json_len);

// A3: Unlock a vault header with password.
//
// Returns enc_key (32 bytes) + hmac_key (32 bytes) = 64 bytes total.
// These are the MEK halves needed for all subsequent operations.
//
// # Safety
// - header_ptr/header_len: valid header bytes (24576 for V4)
// - password_ptr/password_len: valid password
// - out_ptr: capacity >= 64 bytes
// - out_len: valid pointer
int32_t usbvault_vault_unlock(const uint8_t *header_ptr,
                              uintptr_t header_len,
                              const uint8_t *password_ptr,
                              uintptr_t password_len,
                              uint8_t *out_ptr,
                              uintptr_t out_capacity,
                              uintptr_t *out_len);

// A4: Encrypt a VaultIndex JSON blob.
//
// # Safety
// - master_key_ptr: 32-byte encryption key (MEK enc half)
// - index_json_ptr/index_json_len: valid JSON bytes
// - out_ptr: capacity for encrypted blob (JSON + nonce + tag overhead)
int32_t usbvault_vault_encrypt_index(const uint8_t *master_key_ptr,
                                     uintptr_t master_key_len,
                                     const uint8_t *index_json_ptr,
                                     uintptr_t index_json_len,
                                     uint8_t *out_ptr,
                                     uintptr_t out_capacity,
                                     uintptr_t *out_len);

// A5: Decrypt an encrypted VaultIndex blob back to JSON.
//
// # Safety
// - master_key_ptr: 32-byte encryption key
// - encrypted_ptr/encrypted_len: encrypted blob from encrypt_index
// - out_json_ptr: capacity for JSON output
int32_t usbvault_vault_decrypt_index(const uint8_t *master_key_ptr,
                                     uintptr_t master_key_len,
                                     const uint8_t *encrypted_ptr,
                                     uintptr_t encrypted_len,
                                     uint8_t *out_json_ptr,
                                     uintptr_t out_json_capacity,
                                     uintptr_t *out_json_len);

// A6: Encrypt a file as a V2RC chunked AEAD record.
//
// # Safety
// - key_ptr: 32-byte encryption key (per-file key)
// - cipher_id: 2 or 3
// - filename_ptr/filename_len: file name
// - data_ptr/data_len: file content
// - out_ptr: capacity for V2RC record (data + overhead)
int32_t usbvault_vault_encrypt_record(const uint8_t *key_ptr,
                                      uintptr_t key_len,
                                      uint8_t cipher_id,
                                      const uint8_t *filename_ptr,
                                      uintptr_t filename_len,
                                      const uint8_t *data_ptr,
                                      uintptr_t data_len,
                                      uint8_t *out_ptr,
                                      uintptr_t out_capacity,
                                      uintptr_t *out_len);

// A7: Decrypt a V2RC record back to filename + file data.
//
// Output layout: filename_len(4 LE) + filename + data
//
// # Safety
// - key_ptr: 32-byte key
// - record_ptr/record_len: V2RC record bytes
// - out_ptr: capacity for filename_len(4) + filename + data
int32_t usbvault_vault_decrypt_record(const uint8_t *key_ptr,
                                      uintptr_t key_len,
                                      uint8_t cipher_id,
                                      const uint8_t *record_ptr,
                                      uintptr_t record_len,
                                      uint8_t *out_ptr,
                                      uintptr_t out_capacity,
                                      uintptr_t *out_len);

// A8: Read and verify the fail counter from header bytes.
//
// Returns the counter value in out_count on success.
// Returns ERR_FAIL_COUNTER_TAMPERED if HMAC verification fails.
//
// # Safety
// - header_ptr/header_len: valid header bytes
// - hmac_key_ptr: 32-byte HMAC key (MEK hmac half)
// - out_count: valid pointer for writing u32
int32_t usbvault_vault_fail_counter_read(const uint8_t *header_ptr,
                                         uintptr_t header_len,
                                         const uint8_t *hmac_key_ptr,
                                         uintptr_t hmac_key_len,
                                         uint32_t *out_count);

// A9: Increment the fail counter and return updated header bytes.
//
// # Safety
// - header_ptr/header_len: valid header bytes
// - hmac_key_ptr: 32-byte HMAC key
// - out_ptr: capacity >= header size (24576 for V4)
int32_t usbvault_vault_fail_counter_increment(const uint8_t *header_ptr,
                                              uintptr_t header_len,
                                              const uint8_t *hmac_key_ptr,
                                              uintptr_t hmac_key_len,
                                              uint8_t *out_ptr,
                                              uintptr_t out_capacity,
                                              uintptr_t *out_len);

// A10: Reset the fail counter to 0 and return updated header bytes.
//
// Called after successful unlock.
//
// # Safety
// - header_ptr/header_len: valid header bytes
// - hmac_key_ptr: 32-byte HMAC key
// - out_ptr: capacity >= header size
int32_t usbvault_vault_fail_counter_reset(const uint8_t *header_ptr,
                                          uintptr_t header_len,
                                          const uint8_t *hmac_key_ptr,
                                          uintptr_t hmac_key_len,
                                          uint8_t *out_ptr,
                                          uintptr_t out_capacity,
                                          uintptr_t *out_len);

// A11: Commit a new index — flip active slot, update offset/length, increment counters.
//
// This is the atomic dual-index commit operation.
//
// # Safety
// - header_ptr/header_len: valid header bytes
// - hmac_key_ptr: 32-byte HMAC key
// - new_index_offset/new_index_length: the offset and size of the newly written index blob
// - out_ptr: capacity >= header size
int32_t usbvault_vault_commit_index(const uint8_t *header_ptr,
                                    uintptr_t header_len,
                                    const uint8_t *hmac_key_ptr,
                                    uintptr_t hmac_key_len,
                                    uint32_t new_index_offset,
                                    uint32_t new_index_length,
                                    uint8_t *out_ptr,
                                    uintptr_t out_capacity,
                                    uintptr_t *out_len);

// Android platform initialization (called from JNI_OnLoad or application startup)
//
// # Safety
// This function is safe to call from any thread.
int32_t usbvault_android_init();

} // extern "C"
