// PH4-FIX: Moved to vault domain
/**
 * QAV Recovery Code Service
 *
 * SG-006: Shamir's Secret Sharing (SSS) for MEK recovery.
 *
 * When a user sets up their vault, recovery codes are generated by splitting
 * the MEK into N shares using Shamir's Secret Sharing over GF(256). Any K
 * shares can reconstruct the original MEK — fewer than K shares reveal
 * nothing about the secret.
 *
 * Architecture:
 *   MEK (64 bytes) → SSS split(n=5, k=3) → 5 recovery shares
 *   Each share = { index: 1-255, data: 64 bytes } → encoded as recovery code
 *   Any 3 of 5 codes → SSS reconstruct → MEK
 *
 * Recovery codes are base32-encoded for human readability and displayed
 * once during setup. They are NOT stored on the server.
 *
 * @module services/recovery
 */

import { randomBytes } from '@/crypto/bridge';
import { logger } from '@/utils/logger';

// ─── Types ───────────────────────────────────────────────────────────

/** A single Shamir's share: (x, y) point on the polynomial */
export interface ShamirShare {
  /** Share index (1-255, the x-coordinate in GF(256)) */
  index: number;
  /** Share data (same length as the secret) */
  data: Uint8Array;
}

/** Recovery code configuration */
export interface RecoveryConfig {
  /** Total number of shares to generate (default: 5) */
  totalShares: number;
  /** Minimum shares needed for recovery (default: 3) */
  threshold: number;
}

const DEFAULT_CONFIG: RecoveryConfig = {
  totalShares: 5,
  threshold: 3,
};

// ─── GF(256) Arithmetic ──────────────────────────────────────────────
// Galois Field GF(2^8) with irreducible polynomial x^8 + x^4 + x^3 + x + 1
// (AES polynomial, 0x11B)

/** Precomputed log table for GF(256) */
const GF256_LOG = new Uint8Array(256);
/** Precomputed exp table for GF(256) */
const GF256_EXP = new Uint8Array(256);

// Build log/exp tables using generator 3
(function buildTables() {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    GF256_EXP[i] = x;
    GF256_LOG[x] = i;
    x = x ^ (x << 1) ^ (x >= 128 ? 0x11b : 0);
    x &= 0xff;
  }
  GF256_EXP[255] = GF256_EXP[0]; // Wrap around
  GF256_LOG[0] = 0; // Convention: log(0) = 0 (never used in valid operations)
})();

/** Multiply two elements in GF(256) */
function gf256Mul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF256_EXP[(GF256_LOG[a] + GF256_LOG[b]) % 255];
}

/** Compute multiplicative inverse in GF(256) */
function gf256Inv(a: number): number {
  if (a === 0) throw new Error('Division by zero in GF(256)');
  return GF256_EXP[255 - GF256_LOG[a]];
}

/** Add/subtract in GF(256) — both are XOR */
function gf256Add(a: number, b: number): number {
  return a ^ b;
}

// ─── Shamir's Secret Sharing ─────────────────────────────────────────

/**
 * Split a secret into N shares using Shamir's Secret Sharing over GF(256).
 * Any K shares can reconstruct the secret; fewer than K reveal nothing.
 *
 * For each byte of the secret:
 *   1. Create a random polynomial of degree (K-1) with the secret byte as constant term
 *   2. Evaluate the polynomial at N distinct non-zero x-coordinates
 *
 * @param secret - The secret to split (arbitrary length)
 * @param n - Total number of shares to generate (2-255)
 * @param k - Minimum shares needed for recovery (2 ≤ k ≤ n)
 * @returns Array of N ShamirShares
 */
export async function splitSecret(
  secret: Uint8Array,
  n: number = DEFAULT_CONFIG.totalShares,
  k: number = DEFAULT_CONFIG.threshold
): Promise<ShamirShare[]> {
  if (k < 2 || k > n) {
    throw new Error(`Invalid threshold: need 2 ≤ k(${k}) ≤ n(${n})`);
  }
  if (n > 255) {
    throw new Error('Cannot create more than 255 shares');
  }
  if (secret.length === 0) {
    throw new Error('Secret cannot be empty');
  }

  // Generate random coefficients for each byte's polynomial
  // Each byte needs (k-1) random coefficients
  const coefficientBytes = await randomBytes(secret.length * (k - 1));

  // Initialize shares
  const shares: ShamirShare[] = [];
  for (let i = 0; i < n; i++) {
    shares.push({
      index: i + 1, // x-coordinates: 1, 2, ..., n (never 0)
      data: new Uint8Array(secret.length),
    });
  }

  // For each byte of the secret
  for (let byteIdx = 0; byteIdx < secret.length; byteIdx++) {
    // Build polynomial coefficients: [secret_byte, random_1, ..., random_{k-1}]
    const coeffs = new Uint8Array(k);
    coeffs[0] = secret[byteIdx]; // Constant term = secret byte
    for (let c = 1; c < k; c++) {
      coeffs[c] = coefficientBytes[byteIdx * (k - 1) + (c - 1)];
    }

    // Evaluate polynomial at each share's x-coordinate
    for (let shareIdx = 0; shareIdx < n; shareIdx++) {
      const x = shares[shareIdx].index;
      let y = 0;
      let xPow = 1; // x^0 = 1

      for (let c = 0; c < k; c++) {
        y = gf256Add(y, gf256Mul(coeffs[c], xPow));
        xPow = gf256Mul(xPow, x);
      }

      shares[shareIdx].data[byteIdx] = y;
    }
  }

  return shares;
}

/**
 * Reconstruct a secret from K or more Shamir shares using Lagrange interpolation.
 *
 * @param shares - At least K shares (from splitSecret)
 * @param secretLength - Expected length of the secret (for validation)
 * @returns Reconstructed secret
 */
export function reconstructSecret(
  shares: ShamirShare[],
  secretLength?: number
): Uint8Array {
  if (shares.length < 2) {
    throw new Error('Need at least 2 shares for reconstruction');
  }

  const dataLength = shares[0].data.length;
  for (const share of shares) {
    if (share.data.length !== dataLength) {
      throw new Error('All shares must have the same data length');
    }
    if (share.index < 1 || share.index > 255) {
      throw new Error(`Invalid share index: ${share.index} (must be 1-255)`);
    }
  }

  // Check for duplicate indices
  const indices = new Set(shares.map((s) => s.index));
  if (indices.size !== shares.length) {
    throw new Error('Duplicate share indices detected');
  }

  const secret = new Uint8Array(dataLength);

  // Lagrange interpolation at x=0 for each byte position
  for (let byteIdx = 0; byteIdx < dataLength; byteIdx++) {
    let result = 0;

    for (let i = 0; i < shares.length; i++) {
      const xi = shares[i].index;
      const yi = shares[i].data[byteIdx];

      // Compute Lagrange basis polynomial at x=0:
      // L_i(0) = Π_{j≠i} (0 - x_j) / (x_i - x_j) = Π_{j≠i} x_j / (x_i - x_j)
      let basis = 1;
      for (let j = 0; j < shares.length; j++) {
        if (i === j) continue;
        const xj = shares[j].index;
        // numerator: 0 - x_j = x_j (in GF(256), additive inverse = identity since a + a = 0)
        // denominator: x_i - x_j = x_i ^ x_j (XOR in GF(256))
        const num = xj;
        const den = gf256Add(xi, xj);
        basis = gf256Mul(basis, gf256Mul(num, gf256Inv(den)));
      }

      result = gf256Add(result, gf256Mul(yi, basis));
    }

    secret[byteIdx] = result;
  }

  if (secretLength !== undefined && secret.length !== secretLength) {
    throw new Error(
      `Reconstructed secret length (${secret.length}) doesn't match expected (${secretLength})`
    );
  }

  return secret;
}

// ─── Recovery Code Encoding ──────────────────────────────────────────

const BASE32_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';

/**
 * Encode a Shamir share as a human-readable recovery code.
 * Format: "R<index>-<base32_groups>" e.g., "R1-ABCD-EFGH-IJKL-..."
 *
 * The first byte encodes the share index, followed by the share data.
 */
export function encodeRecoveryCode(share: ShamirShare): string {
  // Prepend the share index byte
  const payload = new Uint8Array(1 + share.data.length);
  payload[0] = share.index;
  payload.set(share.data, 1);

  // Base32 encode
  const base32 = base32Encode(payload);

  // Group into 4-character blocks separated by dashes
  const groups: string[] = [];
  for (let i = 0; i < base32.length; i += 4) {
    groups.push(base32.substring(i, i + 4));
  }

  return groups.join('-');
}

/**
 * Decode a human-readable recovery code back to a Shamir share.
 * Accepts codes with or without dashes, case-insensitive.
 */
export function decodeRecoveryCode(code: string): ShamirShare {
  // Normalize: remove dashes and whitespace, uppercase
  const cleaned = code.replace(/[-\s]/g, '').toUpperCase();

  // Base32 decode
  const payload = base32Decode(cleaned);

  if (payload.length < 2) {
    throw new Error('Recovery code too short');
  }

  return {
    index: payload[0],
    data: payload.slice(1),
  };
}

// ─── Base32 Helpers ──────────────────────────────────────────────────

function base32Encode(data: Uint8Array): string {
  let result = '';
  let buffer = 0;
  let bitsLeft = 0;

  for (let i = 0; i < data.length; i++) {
    buffer = (buffer << 8) | data[i];
    bitsLeft += 8;

    while (bitsLeft >= 5) {
      bitsLeft -= 5;
      result += BASE32_ALPHABET[(buffer >> bitsLeft) & 0x1f];
    }
  }

  // Handle remaining bits
  if (bitsLeft > 0) {
    result += BASE32_ALPHABET[(buffer << (5 - bitsLeft)) & 0x1f];
  }

  return result;
}

function base32Decode(encoded: string): Uint8Array {
  const bytes: number[] = [];
  let buffer = 0;
  let bitsLeft = 0;

  for (let i = 0; i < encoded.length; i++) {
    const char = encoded[i];
    const value = BASE32_ALPHABET.indexOf(char);
    if (value === -1) {
      throw new Error(`Invalid base32 character: ${char}`);
    }

    buffer = (buffer << 5) | value;
    bitsLeft += 5;

    if (bitsLeft >= 8) {
      bitsLeft -= 8;
      bytes.push((buffer >> bitsLeft) & 0xff);
    }
  }

  return new Uint8Array(bytes);
}

// ─── High-Level Recovery Operations ──────────────────────────────────

/**
 * SG-006: Generate recovery codes for a vault's MEK.
 *
 * Splits the 64-byte MEK into N shares (default 5), requiring K (default 3)
 * to reconstruct. Returns human-readable recovery codes.
 *
 * @param mek - 64-byte Master Encryption Key
 * @param config - Recovery configuration (default: 5 shares, 3 threshold)
 * @returns Array of recovery code strings
 */
export async function generateRecoveryCodes(
  mek: Uint8Array,
  config: RecoveryConfig = DEFAULT_CONFIG
): Promise<string[]> {
  try {
    const shares = await splitSecret(mek, config.totalShares, config.threshold);
    const codes = shares.map(encodeRecoveryCode);

    logger.info(
      `[recovery] Generated ${config.totalShares} recovery codes ` +
      `(threshold: ${config.threshold})`
    );

    return codes;
  } catch (error) {
    logger.error('[recovery] Failed to generate recovery codes:', error);
    throw new Error(
      `Recovery code generation failed: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/**
 * SG-006: Recover a vault's MEK from recovery codes.
 *
 * Accepts K or more recovery code strings and reconstructs the 64-byte MEK.
 *
 * @param codes - Array of recovery code strings (at least K codes)
 * @returns Reconstructed 64-byte MEK
 * @throws Error if codes are insufficient or invalid
 */
export function recoverMEK(codes: string[]): Uint8Array {
  try {
    const shares = codes.map(decodeRecoveryCode);
    const mek = reconstructSecret(shares, 64);

    logger.info(`[recovery] Successfully recovered MEK from ${codes.length} codes`);

    return mek;
  } catch (error) {
    logger.error('[recovery] MEK recovery failed:', error);
    throw new Error(
      `MEK recovery failed: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
