package auth

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"github.com/rs/zerolog/log"
	"golang.org/x/crypto/argon2"
)

// SRP-6a parameters — RFC 7919 ffdhe3072 (3072-bit MODP group), generator g = 2.
// SECURITY FIX (2026-06-25): the previous value of srpN was a fabricated,
// non-prime, hand-typed repeating-hex string AND it did not match the Rust
// client's group, so a real SRP handshake could never have completed. This is
// now the exact ffdhe3072 prime used by the client in
// usbvault-crypto/src/srp_client.rs (srp_params::N_HEX) — the server and client
// MUST share identical N and g. Verifiers generated by the real client (against
// ffdhe3072) validate against this; any verifier created against the old bogus
// modulus is invalid and the account must be re-registered.
const (
	srpN = "FFFFFFFFFFFFFFFFADF85458A2BB4A9AAFDC5620273D3CF1" +
		"D8B9C583CE2D3695A9E13641146433FBCC939DCE249B3EF9" +
		"7D2FE363630C75D8F681B202AEC4617AD3DF1ED5D5FD6561" +
		"2433F51F5F066ED0856365553DED1AF3B557135E7F57C935" +
		"984F0C70E0E68B77E2A689DAF3EFE8721DF158A136ADE735" +
		"30ACCA4F483A797ABC0AB182B324FB61D108A94BB2C8E3FB" +
		"B96ADAB760D7F4681D4F42A3DE394DF4AE56EDE76372BB19" +
		"0B07A7C8EE0A6D709E02FCE1CDF7E2ECC03404CD28342F61" +
		"9172FE9CE98583FF8E4F1232EEF28183C3FE3B1B4C6FAD73" +
		"3BB5FCBC2EC22005C58EF1837D1683B2C6F34A26C1B2EFFA" +
		"886B4238611FCFDCDE355B3B6519035BBC34F4DEF99C0238" +
		"61B46FC9D6E6C9077AD91D2691F7F7EE598CB0FAC186D91C" +
		"AEFE130985139270B4130C93BC437944F4FD4452E2D74DD3" +
		"64F2E21E71F54BFF5CAE82AB9C9DF69EE86D2BC522363A0D" +
		"ABC521979B0DEADA1DBF9A42D5C4484E0ABCD06BFA53DDEF" +
		"3C1B20EE3FD59D7C25E41D2B66C62E37FFFFFFFFFFFFFFFF"
	srpG = 2

	// LOW-FIX: Extracted magic numbers to named constants
	srpSessionTTL       = 5 * time.Minute
	srpEphemeralKeyBits = 256 // Must be at least 256 bits for 3072-bit group
	srpVerifierMinLen   = 32  // Minimum verifier byte length
	srpVerifierMaxLen   = 512 // Maximum verifier byte length
	srpRandomDelayMax   = 100 // Maximum random delay in milliseconds
	srpContextTimeout   = 5 * time.Second

	// Argon2id parameters for SRP verifier hashing (PHASE 2.1)
	// Matching the Rust client's configuration for consistency
	Argon2Memory      = 65536 // 64 MB
	Argon2Time        = 3
	Argon2Parallelism = 4
	Argon2KeyLength   = 32
)

type SRPInitRequest struct {
	Email string `json:"email"`
}

type SRPInitResponse struct {
	Salt      string `json:"salt"`
	B         string `json:"B"`
	SessionID string `json:"session_id"`
}

type SRPVerifyRequest struct {
	SessionID string `json:"session_id"`
	A         string `json:"A"`
	M1        string `json:"M1"`
}

type SRPVerifyResponse struct {
	M2          string `json:"M2"`
	AccessToken string `json:"access_token"`
	// F4: omitempty — populated only for native clients; web clients receive the
	// refresh token in the HttpOnly cookie instead of the JSON body.
	RefreshToken string `json:"refresh_token,omitempty"`
}

type srpServerState struct {
	B string
	// BPrivate is the server's private ephemeral 'b' (RFC 5054), as a base-10
	// string. It MUST be exported and JSON-tagged: the state is marshalled to
	// JSON and stored in Redis at init, then unmarshalled at verify. An
	// unexported field is silently dropped by encoding/json, which previously
	// left b nil at verify and broke (panicked) every SRP login.
	BPrivate         string `json:"b_private"`
	A                *big.Int
	Salt             []byte
	SRPVerifier      []byte
	EmailHash        string
	UserID           string
	CreatedAt        time.Time
	VerifierHashAlgo string // "sha256" (legacy) or "argon2id" (current)
	RequiresRehash   bool   // Flag for transparent rehashing on successful login
}

// HashVerifierArgon2id hashes an SRP verifier using Argon2id for offline attack resistance.
// This replaces the weaker SHA-256 hashing to provide stronger protection against
// dictionary attacks in case the database is compromised.
// PHASE 2.1: Argon2id SRP Verifier hardening
func HashVerifierArgon2id(verifier []byte, salt []byte) []byte {
	return argon2.IDKey(verifier, salt, Argon2Time, Argon2Memory, Argon2Parallelism, Argon2KeyLength)
}

// VerifyVerifier checks an SRP verifier against a hash using the appropriate algorithm.
// Supports both legacy SHA-256 and modern Argon2id to enable transparent migration.
func VerifyVerifier(storedHash []byte, verifier []byte, salt []byte, algo string) bool {
	if algo == "argon2id" {
		computed := HashVerifierArgon2id(verifier, salt)
		return subtle.ConstantTimeCompare(storedHash, computed) == 1
	}
	// Default to SHA-256 for backwards compatibility (legacy)
	computed := sha256.Sum256(verifier)
	return subtle.ConstantTimeCompare(storedHash, computed[:]) == 1
}

func HandleSRPInit(pool *pgxpool.Pool, redisClient *redis.Client, lockoutSvc *AccountLockoutService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req SRPInitRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "invalid request", http.StatusBadRequest)
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), srpContextTimeout)
		defer cancel()

		// Look up user by email hash
		emailHash := hashEmail(req.Email)

		// Check account lockout status
		lockoutStatus, err := lockoutSvc.CheckLockout(ctx, emailHash)
		if err != nil {
			log.Error().Err(err).Str("email", req.Email).Msg("failed to check lockout status")
			http.Error(w, "internal error", http.StatusInternalServerError)
			return
		}

		// If account is locked, return 429 Too Many Requests
		if lockoutStatus.Locked {
			retryAfter := int(lockoutStatus.LockedUntil.Sub(time.Now()).Seconds())
			if retryAfter <= 0 {
				retryAfter = 1
			}
			w.Header().Set("Retry-After", fmt.Sprintf("%d", retryAfter))
			log.Warn().Str("email", req.Email).Int("retry_after_seconds", retryAfter).Msg("login attempt on locked account")
			http.Error(w, "account locked due to too many failed login attempts", http.StatusTooManyRequests)
			return
		}

		// Apply progressive delay if there are previous failed attempts
		if lockoutStatus.Delay > 0 {
			time.Sleep(lockoutStatus.Delay)
		}

		var userID string
		var srpSalt, srpVerifier []byte
		var verifierHashAlgo string
		var needsReReg bool

		// PHASE 2.1: Read verifier hash algorithm; default to "sha256" for backwards compatibility
		err = pool.QueryRow(ctx,
			`SELECT id, srp_salt, srp_verifier, COALESCE(srp_verifier_hash_algorithm, 'sha256'), srp_needs_reregistration FROM users WHERE email_hash = $1 AND deleted_at IS NULL`,
			emailHash,
		).Scan(&userID, &srpSalt, &srpVerifier, &verifierHashAlgo, &needsReReg)

		if err != nil {
			// User not found - perform constant-time dummy computation to prevent timing attacks
			log.Debug().Err(err).Str("email", req.Email).Msg("user not found")
			// Generate dummy B to avoid timing leaks
			dummyB := computeDummyB()
			time.Sleep(time.Duration(randomDelayMS()) * time.Millisecond)
			http.Error(w, "invalid credentials", http.StatusUnauthorized)
			_ = dummyB // prevent optimization
			return
		}

		// #65: accounts that predate the ffdhe3072 SRP modulus fix may carry a verifier
		// computed against the OLD modulus, which can never validate under the new one
		// (and x is unrecoverable server-side). Rather than letting login fail as a
		// confusing "invalid credentials", signal the client to re-register. This is
		// returned only for an already-enumerable account and exposes no secret material.
		if needsReReg {
			log.Info().Str("email_hash", emailHash).Msg("#65: login blocked — account must re-register after SRP modulus fix")
			writeReRegistrationRequired(w)
			return
		}

		// Parse SRP group parameters
		N := new(big.Int)
		N.SetString(srpN, 16)
		g := big.NewInt(srpG)

		// Compute k = H(PAD(N) | PAD(g)) per RFC 5054
		k := computeSRPk(N, g)

		// DV-006 FIX: Validate verifier byte length before big.Int conversion
		if len(srpVerifier) < srpVerifierMinLen || len(srpVerifier) > srpVerifierMaxLen {
			log.Warn().Int("verifier_len", len(srpVerifier)).Msg("SRP verifier has invalid length")
			dummyB := computeDummyB()
			time.Sleep(time.Duration(randomDelayMS()) * time.Millisecond)
			http.Error(w, "invalid credentials", http.StatusUnauthorized)
			_ = dummyB
			return
		}

		// Parse verifier from hex-encoded bytes
		v := new(big.Int)
		v.SetBytes(srpVerifier)

		// Generate random server ephemeral key b (must be at least 256 bits for 3072-bit group)
		b, err := randomBigInt(srpEphemeralKeyBits)
		if err != nil {
			log.Error().Err(err).Msg("failed to generate SRP ephemeral key")
			http.Error(w, "internal error", http.StatusInternalServerError)
			return
		}

		// Compute B = k*v + g^b mod N
		gb := new(big.Int).Exp(g, b, N)
		kv := new(big.Int).Mul(k, v)
		kv.Mod(kv, N)
		B := new(big.Int).Add(kv, gb)
		B.Mod(B, N)

		// Ensure B != 0 mod N
		if B.Sign() == 0 {
			log.Error().Msg("SRP computation resulted in B=0, rejecting")
			http.Error(w, "internal error", http.StatusInternalServerError)
			return
		}

		// Store state in Redis with 5 minute TTL
		sessionID := uuid.New().String()
		// PHASE 2.1: Track whether verifier needs rehashing on successful login
		requiresRehash := verifierHashAlgo != "argon2id"
		state := srpServerState{
			B:                B.String(),
			BPrivate:         b.String(),
			Salt:             srpSalt,
			SRPVerifier:      srpVerifier,
			EmailHash:        emailHash,
			UserID:           userID,
			CreatedAt:        time.Now(),
			VerifierHashAlgo: verifierHashAlgo,
			RequiresRehash:   requiresRehash,
		}

		stateJSON, _ := json.Marshal(state)
		redisClient.Set(ctx, "srp:"+sessionID, stateJSON, srpSessionTTL)

		// Encode salt and B as hex strings for JSON response
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(SRPInitResponse{
			Salt:      hex.EncodeToString(srpSalt),
			B:         B.String(),
			SessionID: sessionID,
		})
	}
}

func HandleSRPVerify(pool *pgxpool.Pool, redisClient *redis.Client, lockoutSvc *AccountLockoutService, auditSvc interface {
	LogAction(ctx context.Context, userID string, actionType string, encryptedDetail []byte) error
}) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req SRPVerifyRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "invalid request", http.StatusBadRequest)
			return
		}

		ctx, cancel := context.WithTimeout(r.Context(), srpContextTimeout)
		defer cancel()

		// Retrieve state from Redis
		stateJSON, err := redisClient.Get(ctx, "srp:"+req.SessionID).Bytes()
		if err != nil {
			log.Debug().Err(err).Str("session_id", req.SessionID).Msg("session not found or expired")
			http.Error(w, "invalid session", http.StatusUnauthorized)
			return
		}

		// Delete session immediately to prevent replay attacks
		redisClient.Del(ctx, "srp:"+req.SessionID)

		var state srpServerState
		if err := json.Unmarshal(stateJSON, &state); err != nil {
			log.Warn().Err(err).Msg("failed to unmarshal SRP state")
			http.Error(w, "invalid session", http.StatusUnauthorized)
			return
		}

		// CR-2 FIX: Validate required fields in deserialized SRP state
		// Prevents processing with zero-value fields from corrupted/tampered Redis data
		if state.UserID == "" || state.EmailHash == "" || len(state.Salt) == 0 || len(state.SRPVerifier) == 0 || state.B == "" || state.BPrivate == "" {
			log.Warn().Str("session_id", req.SessionID).Msg("SRP state missing required fields")
			http.Error(w, "invalid session", http.StatusUnauthorized)
			return
		}

		// Parse SRP group parameters
		N := new(big.Int)
		N.SetString(srpN, 16)
		_ = big.NewInt(srpG) // g used by init handler; verify only needs N

		// Parse client ephemeral A from base-10 string
		A := new(big.Int)
		if _, ok := A.SetString(req.A, 10); !ok {
			log.Warn().Str("user_id", state.UserID).Msg("invalid A value format")
			// Record failed attempt
			lockoutSvc.RecordFailedAttempt(ctx, state.EmailHash)
			http.Error(w, "authentication failed", http.StatusUnauthorized)
			return
		}

		// Validate A: must not be 0 mod N
		if A.Sign() <= 0 || A.Cmp(N) >= 0 {
			log.Warn().Str("user_id", state.UserID).Msg("A out of valid range")
			// Record failed attempt
			lockoutSvc.RecordFailedAttempt(ctx, state.EmailHash)
			http.Error(w, "authentication failed", http.StatusUnauthorized)
			return
		}

		// Compute scrambler u = H(PAD(A) | PAD(B))
		u := computeSRPu(A, state.B)

		// RFC 5054: the protocol MUST abort if u == 0 — otherwise the verifier
		// term v^u collapses to 1 and an attacker could authenticate without
		// knowing the password.
		if u.Sign() == 0 {
			log.Warn().Str("user_id", state.UserID).Msg("SRP scrambler u == 0, rejecting")
			lockoutSvc.RecordFailedAttempt(ctx, state.EmailHash)
			http.Error(w, "authentication failed", http.StatusUnauthorized)
			return
		}

		// Parse verifier and compute shared secret S = (A * v^u)^b mod N
		v := new(big.Int)
		v.SetBytes(state.SRPVerifier)

		// Recover the server private ephemeral b persisted at init (see
		// srpServerState.BPrivate). Parsing failure means tampered/corrupt state.
		b := new(big.Int)
		if _, ok := b.SetString(state.BPrivate, 10); !ok {
			log.Warn().Str("user_id", state.UserID).Msg("invalid SRP server state: b_private not parseable")
			http.Error(w, "invalid session", http.StatusUnauthorized)
			return
		}

		// Compute S = (A * v^u)^b mod N
		vu := new(big.Int).Exp(v, u, N)
		Avu := new(big.Int).Mul(A, vu)
		Avu.Mod(Avu, N)
		S := new(big.Int).Exp(Avu, b, N)

		// Compute K = H(PAD(S)) — canonical convention (PAD to srpPadLen),
		// matching the Rust client so the derived session key is byte-identical.
		K := sha256.Sum256(padBigInt(S))

		// Verify client proof M1 = H(A, B, K) per RFC 5054
		M1Computed := computeSRPProofM1(A, state.B, K[:])

		// CR-001 FIX: Use crypto/subtle.ConstantTimeCompare instead of custom bytesEqual
		M1Hex := hex.EncodeToString(M1Computed[:])
		if subtle.ConstantTimeCompare([]byte(req.M1), []byte(M1Hex)) != 1 {
			log.Warn().Str("user_id", state.UserID).Msg("SRP M1 verification failed")
			// Record failed attempt
			lockoutSvc.RecordFailedAttempt(ctx, state.EmailHash)
			http.Error(w, "authentication failed", http.StatusUnauthorized)
			return
		}

		// Check session age to prevent replay
		if time.Since(state.CreatedAt) > srpSessionTTL {
			log.Warn().Str("user_id", state.UserID).Msg("SRP session expired")
			// Record failed attempt for expired session
			lockoutSvc.RecordFailedAttempt(ctx, state.EmailHash)
			http.Error(w, "session expired", http.StatusUnauthorized)
			return
		}

		// Compute server proof M2 = H(A, M1, K)
		M2Computed := computeSRPProofM2(A, M1Computed[:], K[:])

		// Issue JWT tokens
		accessToken, refreshToken, err := GenerateTokenPair(state.UserID, "web")
		if err != nil {
			log.Error().Err(err).Str("user_id", state.UserID).Msg("token generation failed")
			http.Error(w, "token generation failed", http.StatusInternalServerError)
			return
		}

		// Reset lockout attempts on successful authentication
		if err := lockoutSvc.ResetAttempts(ctx, state.EmailHash); err != nil {
			log.Error().Err(err).Str("user_id", state.UserID).Msg("failed to reset lockout attempts")
		}

		// SECURITY FIX (2026-06-25): the previous "transparent Argon2id verifier
		// rehash" was REMOVED. It overwrote srp_verifier in the DB with
		// Argon2id(v), but the SRP handshake uses the verifier v directly
		// (v.SetBytes(state.SRPVerifier)). After one successful login the stored
		// value became Argon2id(v), so the NEXT login computed with the wrong v,
		// M1 verification failed, and the user was locked out. Hashing the stored
		// verifier also yields zero offline-attack benefit — the server must keep
		// v to run SRP at all. Offline resistance comes from the client's
		// Argon2id password->x derivation, not from hashing v. The verifier is
		// stored and used as-is.

		// Log successful authentication
		auditSvc.LogAction(ctx, state.UserID, "AUTH_LOGIN", []byte("SRP"))

		// F4: Set the refresh token as an HttpOnly, Secure, SameSite=Strict
		// cookie for web clients so JS never holds the long-lived refresh
		// credential (XSS cannot exfiltrate it). Native clients ignore the
		// cookie and read the refresh token from the JSON body below, storing
		// it in the OS keychain/secure-store.
		setRefreshCookie(w, refreshToken)

		// F4 (no refresh token in web responses): include the refresh token in the
		// JSON body ONLY for native clients (no browser Origin/Referer/cookie).
		// Web clients rely on the cookie set above.
		resp := SRPVerifyResponse{
			M2:          hex.EncodeToString(M2Computed[:]),
			AccessToken: accessToken,
		}
		if !IsWebRequest(r) {
			resp.RefreshToken = refreshToken
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func hashEmail(email string) string {
	h := sha256.Sum256([]byte(email))
	return hex.EncodeToString(h[:])
}

// CR-003 FIX: Return error instead of panicking on crypto failure
func randomBigInt(bits int) (*big.Int, error) {
	b := make([]byte, bits/8)
	if _, err := io.ReadFull(rand.Reader, b); err != nil {
		return nil, fmt.Errorf("crypto/rand failure: %w", err)
	}
	return new(big.Int).SetBytes(b), nil
}

// srpPadLen is the canonical PAD width for all SRP hash inputs: the byte length
// of N (RFC 7919 ffdhe3072 => 3072 bits => 384 bytes). Per the canonical
// SRP-6a convention shared with the Rust client (usbvault-crypto/src/srp_client.rs),
// EVERY big-integer operand fed into a hash (N, g, A, B, S) is left-zero-padded,
// big-endian, to exactly this width before hashing. Hashing variable-width
// big.Int.Bytes() output (which strips leading zero bytes) was the root cause of
// the Go<->Rust interop break: the same numeric value could hash differently
// depending on its high byte.
const srpPadLen = 384

// padBigInt left-zero-pads x's big-endian byte representation to srpPadLen
// bytes. This is the canonical PAD(x) used on BOTH the Go server and the Rust
// client so that k, u, K, M1 and M2 are byte-identical across implementations.
func padBigInt(x *big.Int) []byte {
	xb := x.Bytes()
	out := make([]byte, srpPadLen)
	// Right-align; if xb somehow exceeds srpPadLen, copy keeps the low bytes.
	if len(xb) <= srpPadLen {
		copy(out[srpPadLen-len(xb):], xb)
	} else {
		copy(out, xb[len(xb)-srpPadLen:])
	}
	return out
}

// computeSRPk computes k = H(PAD(N) || PAD(g)) per RFC 5054, canonical convention.
func computeSRPk(N, g *big.Int) *big.Int {
	h := sha256.Sum256(bytes.Join([][]byte{padBigInt(N), padBigInt(g)}, nil))
	k := new(big.Int)
	k.SetBytes(h[:])
	return k
}

// computeSRPu computes u = H(PAD(A) || PAD(B)) per RFC 5054, canonical convention.
func computeSRPu(A *big.Int, bStr string) *big.Int {
	B := new(big.Int)
	B.SetString(bStr, 10)

	h := sha256.Sum256(bytes.Join([][]byte{padBigInt(A), padBigInt(B)}, nil))
	u := new(big.Int)
	u.SetBytes(h[:])
	return u
}

// computeSRPProofM1 computes M1 = H(PAD(A) || PAD(B) || K), canonical convention.
// A and B are padded to srpPadLen; K is the raw 32-byte session-key hash.
func computeSRPProofM1(A *big.Int, bStr string, K []byte) [32]byte {
	B := new(big.Int)
	B.SetString(bStr, 10)

	h := sha256.New()
	h.Write(padBigInt(A))
	h.Write(padBigInt(B))
	h.Write(K)

	var m1 [32]byte
	copy(m1[:], h.Sum(nil))
	return m1
}

// computeSRPProofM2 computes M2 = H(PAD(A) || M1 || K), canonical convention.
// A is padded to srpPadLen; M1 (32 bytes) and K (32 bytes) are raw.
func computeSRPProofM2(A *big.Int, M1, K []byte) [32]byte {
	h := sha256.New()
	h.Write(padBigInt(A))
	h.Write(M1)
	h.Write(K)

	var m2 [32]byte
	copy(m2[:], h.Sum(nil))
	return m2
}

// computeDummyB generates a dummy B value to prevent timing attacks
func computeDummyB() *big.Int {
	N := new(big.Int)
	N.SetString(srpN, 16)
	g := big.NewInt(srpG)
	b, err := randomBigInt(256)
	if err != nil {
		// Fallback: use a fixed value for timing attack prevention
		// This is acceptable because dummy B is never used cryptographically
		b = big.NewInt(12345)
	}
	gb := new(big.Int).Exp(g, b, N)
	return gb
}

// randomDelayMS returns a random delay in milliseconds to prevent timing attacks
func randomDelayMS() int {
	delayBytes := make([]byte, 2)
	rand.Read(delayBytes)
	return int(uint16(delayBytes[0])<<8|uint16(delayBytes[1])) % srpRandomDelayMax
}

// bytesEqual is deprecated in favor of crypto/subtle.ConstantTimeCompare
// Kept for backward compatibility in tests
func bytesEqual(a, b []byte) bool {
	return subtle.ConstantTimeCompare(a, b) == 1
}
